spring:
  datasource:
    url: jdbc:postgresql://${DB_HOST:postgres}:${DB_PORT:5432}/${DB_NAME:elevatordb}
    driver-class-name: org.postgresql.Driver
    username: ${DB_USERNAME:elevator_user}
    password: ${DB_PASSWORD:elevator_pass}
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
  h2:
    console:
      enabled: false

logging:
  level:
    com.example.elevator: WARN
